import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";
const root=resolve(import.meta.dirname,"..");
const required=["index.html","assets/styles.css","assets/site-data.js","assets/app.js","api/chat.js","assets/fonts/oxanium-latin.woff2","assets/images/hero.webp","assets/images/another-house-og-20260727.jpg","docs/research-sources.md","vercel.json"];
await Promise.all(required.map(file=>access(resolve(root,file))));
const html=await readFile(resolve(root,"index.html"),"utf8");
const js=await readFile(resolve(root,"assets/app.js"),"utf8");
const data=await readFile(resolve(root,"assets/site-data.js"),"utf8");
const updates=await readFile(resolve(root,"assets/content-updates.js"),"utf8");
const chatApi=await readFile(resolve(root,"api/chat.js"),"utf8");
const refs=[...html.matchAll(/(?:src|href)="(\/assets\/[^"?]+)(?:\?[^"]*)?"/g)].map(match=>match[1]);
await Promise.all(refs.map(ref=>access(resolve(root,ref.slice(1)))));
for(const approvedGuestDetail of ["another1234"]) if(!(data+updates).includes(approvedGuestDetail)) throw new Error("Approved guest detail is missing: "+approvedGuestDetail);
if(/FAQ|faq|guide-extay|extay-release/i.test(html+js+data+updates)) throw new Error("Legacy EXTAY or FAQ content detected");
new Function(js); new Function(data); new Function("module","require","process","fetch","AbortSignal",chatApi);
console.log("Validated "+required.length+" required files and "+refs.length+" local asset references.");
